version: '3.8'
services:
  mariadb:
    image: mariadb:latest
    container_name: my-mariadb
    environment:
      - MARIADB_ROOT_PASSWORD=root
    ports:
      - '3306:3306'
    volumes:
      - 'C:/Developer/mariadb/datadir:/var/lib/mysql'